-- Includes all lua files

require("jschill.plugins-setup")
require("jschill.core.options")
require("jschill.core.keymaps")
require("jschill.core.colorscheme")
require("jschill.plugins.comment")
require("jschill.plugins.nvim-tree")
require("jschill.plugins.lualine")
require("jschill.plugins.telescope")
require("jschill.plugins.nvim-cmp")
require("jschill.plugins.lsp.mason")
require("jschill.plugins.lsp.lspsaga")
require("jschill.plugins.lsp.lspconfig")
require("jschill.plugins.lsp.null-ls")
require("jschill.plugins.autopairs")
require("jschill.plugins.treesitter")
require("jschill.plugins.gitsigns")
require("jschill.plugins.dashboard")
require("jschill.plugins.indent")
require("jschill.plugins.hop")
